"""add error_message to meeting

Revision ID: c3ecfaa88bd1
Revises: 001
Create Date: 2026-05-24 19:29:22.971631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3ecfaa88bd1'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action_item', 'task',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_action_deadline'), table_name='action_item', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_action_meeting_id'), table_name='action_item', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_action_owner'), table_name='action_item', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_action_source_chunk'), table_name='action_item', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_action_status'), table_name='action_item', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('decision_conflict', 'topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('decision_conflict', 'current_decision',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('decision_conflict', 'previous_decision',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('decision_conflict', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_conflict_current_chunk'), table_name='decision_conflict')
    op.drop_index(op.f('idx_conflict_level'), table_name='decision_conflict')
    op.drop_index(op.f('idx_conflict_previous_meeting'), table_name='decision_conflict')
    op.alter_column('decision_record', 'topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('decision_record', 'decision',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_decision_meeting_id'), table_name='decision_record')
    op.drop_index(op.f('idx_decision_source'), table_name='decision_record')
    op.drop_index(op.f('idx_decision_topic'), table_name='decision_record')
    op.drop_index(op.f('idx_job_meeting_id'), table_name='job')
    op.drop_index(op.f('idx_job_status'), table_name='job')
    op.add_column('meeting', sa.Column('error_message', sa.String(length=1000), nullable=True))
    op.alter_column('meeting', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_meeting_created_at'), table_name='meeting', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_meeting_started_at'), table_name='meeting', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_meeting_status'), table_name='meeting', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_meeting_tag_meeting_id'), table_name='meeting_tag')
    op.drop_index(op.f('idx_meeting_tag_tag'), table_name='meeting_tag')
    op.alter_column('qa_citation', 'text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_citation_chunk_id'), table_name='qa_citation')
    op.drop_index(op.f('idx_citation_qa_history_id'), table_name='qa_citation')
    op.alter_column('qa_history', 'question',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('qa_history', 'answer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_qa_created_at'), table_name='qa_history')
    op.drop_index(op.f('idx_qa_meeting_id'), table_name='qa_history')
    op.drop_index(op.f('idx_qa_question_embedding'), table_name='qa_history', postgresql_ops={'question_embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('summary', 'overview',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('summary', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('idx_summary_embedding'), table_name='summary', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_summary_meeting_id'), table_name='summary')
    op.alter_column('summary_decision', 'decision',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_summary_decision_summary_id'), table_name='summary_decision')
    op.alter_column('summary_open_question', 'question',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_summary_question_summary_id'), table_name='summary_open_question')
    op.alter_column('summary_risk', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_summary_risk_summary_id'), table_name='summary_risk')
    op.alter_column('summary_topic', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_summary_topic_summary_id'), table_name='summary_topic')
    op.alter_column('transcript_chunk', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_chunk_embedding'), table_name='transcript_chunk', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_chunk_meeting_id'), table_name='transcript_chunk', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_chunk_speaker'), table_name='transcript_chunk', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_chunk_start_time'), table_name='transcript_chunk', postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_chunk_start_time'), 'transcript_chunk', ['meeting_id', 'start'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_chunk_speaker'), 'transcript_chunk', ['speaker'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_chunk_meeting_id'), 'transcript_chunk', ['meeting_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_chunk_embedding'), 'transcript_chunk', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('transcript_chunk', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_summary_topic_summary_id'), 'summary_topic', ['summary_id'], unique=False)
    op.alter_column('summary_topic', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_summary_risk_summary_id'), 'summary_risk', ['summary_id'], unique=False)
    op.alter_column('summary_risk', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_summary_question_summary_id'), 'summary_open_question', ['summary_id'], unique=False)
    op.alter_column('summary_open_question', 'question',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_summary_decision_summary_id'), 'summary_decision', ['summary_id'], unique=False)
    op.alter_column('summary_decision', 'decision',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_summary_meeting_id'), 'summary', ['meeting_id'], unique=False)
    op.create_index(op.f('idx_summary_embedding'), 'summary', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('summary', 'generated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('summary', 'overview',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_qa_question_embedding'), 'qa_history', ['question_embedding'], unique=False, postgresql_ops={'question_embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_qa_meeting_id'), 'qa_history', ['meeting_id'], unique=False)
    op.create_index(op.f('idx_qa_created_at'), 'qa_history', ['created_at'], unique=False)
    op.alter_column('qa_history', 'answer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('qa_history', 'question',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_citation_qa_history_id'), 'qa_citation', ['qa_history_id'], unique=False)
    op.create_index(op.f('idx_citation_chunk_id'), 'qa_citation', ['chunk_id'], unique=False)
    op.alter_column('qa_citation', 'text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_meeting_tag_tag'), 'meeting_tag', ['tag'], unique=False)
    op.create_index(op.f('idx_meeting_tag_meeting_id'), 'meeting_tag', ['meeting_id'], unique=False)
    op.create_index(op.f('idx_meeting_status'), 'meeting', ['status'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_meeting_started_at'), 'meeting', ['started_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_meeting_created_at'), 'meeting', ['created_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('meeting', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('meeting', 'error_message')
    op.create_index(op.f('idx_job_status'), 'job', ['status'], unique=False)
    op.create_index(op.f('idx_job_meeting_id'), 'job', ['meeting_id'], unique=False)
    op.create_index(op.f('idx_decision_topic'), 'decision_record', ['topic'], unique=False)
    op.create_index(op.f('idx_decision_source'), 'decision_record', ['source_chunk_id'], unique=False)
    op.create_index(op.f('idx_decision_meeting_id'), 'decision_record', ['meeting_id'], unique=False)
    op.alter_column('decision_record', 'decision',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('decision_record', 'topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_conflict_previous_meeting'), 'decision_conflict', ['previous_meeting_id'], unique=False)
    op.create_index(op.f('idx_conflict_level'), 'decision_conflict', ['level'], unique=False)
    op.create_index(op.f('idx_conflict_current_chunk'), 'decision_conflict', ['current_source_chunk_id'], unique=False)
    op.alter_column('decision_conflict', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('decision_conflict', 'previous_decision',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('decision_conflict', 'current_decision',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('decision_conflict', 'topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_action_status'), 'action_item', ['status'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_action_source_chunk'), 'action_item', ['source_chunk_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_action_owner'), 'action_item', ['owner'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_action_meeting_id'), 'action_item', ['meeting_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_action_deadline'), 'action_item', ['deadline'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('action_item', 'task',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
